### ISSUE TITLE
 Discrepancies Found Between Documentation and CPSOLVER.for Code

### ISSUE THREAD

**Issue by vikramroybarc** [TarletonGroup/CrystalPlasticity#5]
Subject: Discrepancies Found Between Documentation and CPSOLVER.for Code

Dear ED Tarleton Group,

I am writing to bring to your attention certain inconsistencies I have observed between the code and the formulae mentioned in the documentation file for CPSOLVER.for.

Specifically, these deviations pertain to the CP_forwardgradientPredictor subroutine. In the documentation, the formula is presented as C:P + WSigma - SigmaW, whereas in the code, it is programmed as C:SchmidVector + SigmaW - WSigma.

Additionally, I have noticed a variation in the calculation of P and SchmidVector. According to the documentation, P is defined as 0.5*(Schmid + Transpose(Schmid)). However, in the SchmidVector variable, the shear terms are doubled, indicated as SchmidVector(4, 5, 6) = (Schmid + Transpose(Schmid)).

I kindly request your assistance in clarifying which version is the accurate one. It would be greatly appreciated if you could spare some time to address this matter as soon as possible.

Thank you for your attention to this matter, and I look forward to your prompt reply.

Best regards,
Vikram Roy
India

**Comment by EralpDemir** [comment]
Hi Vikram,

Many thanks for raising these issues, my answers are as follows:

Q1. Specifically, these deviations pertain to the CP_forwardgradientPredictor subroutine. In the documentation, the formula is presented as C:P + WSigma - SigmaW, whereas in the code, it is programmed as C:SchmidVector + SigmaW - WSigma.

A1. The rotation correction is stored in a variable called beta. The calculation is done using symbolic math. As you have suggested we missed a negative sign here, probably it remained due to an earlier derivation. I am sharing the symbolic math tool I used to calculate the beta. It must be corrected with "-sign". For our cases, we had small rotations and that is probably why it did not matter much. Thanks anyway for the careful look and correction.


Q2. Additionally, I have noticed a variation in the calculation of P and SchmidVector. According to the documentation, P is defined as 0.5*(Schmid + Transpose(Schmid)). However, in the SchmidVector variable, the shear terms are doubled, indicated as SchmidVector(4, 5, 6) = (Schmid + Transpose(Schmid)).

A2. Yes, the shear terms are doubled and they must be. The elasticity is for simple shears, not for engineering shear strains. Therefore, the shear strains terms that come out of P matrix shall be multipled with 2. Instead of using P and mutliplying the shear terms with 2, we used the readily available vectorized Schmid tensor that has already the shear corrections.

[symbolic.txt](https://github.com/TarletonGroup/CrystalPlasticity/files/11574080/symbolic.txt)

I hope these answer your corrections and feel free to give any further updates since the code is in development stage now.

Bests,
Eralp

**Comment by vikramroybarc** [comment]
Dear Eralp,

I appreciate your prompt response.

However, I still have some concerns regarding the usage of the P vector and Vectorized SchmidVector, as mentioned in our previous discussions. In the documentation, the calculation of stress increments (deltaSigma) is expressed as follows:

dsigma = matmul(Cs, dstran) - sigma_t * dev - matmul(ddemsd, dgamma)

In this equation, the SchmidVector is utilized for the calculation of the ddemsd variable instead of the P vector. Based on our previous conversation, I believe the P vector should be used in this context, as no shear correction is required, as you have explained.

Here is the specific excerpt from the documentation:
![1](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/f20d8b31-c367-4a78-aeed-838d998d835d)


Thank you for your attention to this matter.

Best regards,
Vikram Ro

**Comment by EralpDemir** [comment]
Thanks again Vikram.

The P-matrix multiplies with the elasticity. But the elasticity is for the vectorized form of strains and the shear components are in the form of simple shears, not engineering shears. You need to use a shear correction before mapping into elasticity. The tensor notation with inner product can also be used but it more computationally intensive than using direct/matrix notation that is why preferred it.

The calculation for the overall mapping is correct, I double checked it to ensure.

Bests,
Eralp

**Comment by vikramroybarc** [comment]
Dear Eralp,

I want to express my gratitude for your helpful responses. I am pleased to inform you that I now have a better understanding of the Shear Correction concept we discussed earlier.

To provide additional clarity for anyone following this discussion, I have attached a paragraph from the Introduction to Computational Plasticity by Fionne Dunne. This paragraph elaborates on the topic and may serve as a helpful reference.

Please find the attached paragraph here: 
[2](https://github.com/TarletonGroup/CrystalPlasticity/assets/126593761/fd63bd4e-cf57-48d0-bf61-dc97ce2f256b).

Thank you once again for your assistance.

Best regards,
Vikram Roy

**Comment by EralpDemir** [comment]
Thank you Vikram for your valuable comments. Please feel free to let us know if you notice any other issues.

I have made the necessary correction and posted an updated version. 

Many thanks,
Eralp
