### ISSUE TITLE
Some issues when material-id=3

### ISSUE THREAD

**Issue by Wzzz603** [TarletonGroup/CrystalPlasticity#78]
Hello,Eralp
I followed the youtube video above (Dream3D2Abaqus-UMAT polycrystal) and successfully ran your program through step1-3,especially step2(Dream3D2Abaqus('testcase',2,12)) 
but when I tried to compute hcp( Dream3D2Abaqus('testcase',3,12)), the following error occurs in abaqus:
The executable standard.exe aborted with system error code 1073741819. Please check the .dat, .msg, and .sta files for error messages if the files exist.  If there are no error messages and you cannot resolve the problem, please run the command "abaqus job=support information=support" to report and save your system information.  Use the same command to run Abaqus that you used when the problem occurred.  Please contact your local Abaqus support office and send them the input file, the file support.log which you just created, the executable name, and the error code.
Is there a way to fix this error?
Looking forward to your answer,thank you!
lucas

**Comment by EralpDemir** [comment]
Hi, 
Thanks for your interest in using our code.

In the material ID-3, 30 number of slip systems were used that are all possible for HCP material.

You need to change the "maxnslip" parameter in "userinputs.f" to the maximum number of slip systems requested in the analysis. It is set to "12" by default. This should solve the issue.

Best,
Eralp

**Comment by Wzzz603** [comment]
Hello,Eralp：
Thanks for getting back to me, this did get my program to run successfully.
Unlike material ID=2, I tried to get this RVE to do a 0.1 displacement as the video says, but when the program ran to 0.07, a non-convergence occurred (Too many attempts made for this increment)and I changed the IA to 100 still didn't fix the problem.
Is there any way to fix this problem please?
Looking forward to your answer again!
Lucas

**Comment by EralpDemir** [comment]
Hi,
It might be related to material properties. You may try reducing the time steps or set a conservative value for increasing the time step. You may use set the variable "pastefront=1.1" in "userinputs.f" for that.
Best
